apiVersion: v2
name: serving
version: 1.15.4
kubeVersion: ">=1.28.0"
description: "Knative Serving"
sources:
- https://github.com/knative/serving
maintainers:
- name: katallaxie
appVersion: "v1.15.4"
