apiVersion: v2
name: eventing
version: 1.0.1
description: |
  A channel layer for Knative Eventing that uses NATS Streaming as the underlying messaging system.
home: https://github.com/knative-extensions/eventing-natss
maintainers:
  - name: katallaxie
icon: https://raw.githubusercontent.com/nats-io/nats-server/main/logos/nats-server.png
appVersion: "v1.17.0"
dependencies:
  - name: eventing-jsm
    version: 1.17.0
    condition: jsm.enabled
  - name: eventing-natss
    version: 1.17.0
    condition: natss.enabled
