name: vcluster-platform

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        version: [latest, 4.11.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4
      - id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ${{ github.workspace }}/images/vcluster-platform
          build-args: |
            VCLUSTER_VERSION=${{ matrix.version }}
          push: true
          tags: ${{ env.REGISTRY }}/zeiss/charts/vcluster-platform:${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
